F3urr
Listenbourg/GenerateurCNI pull request #13
Opened 2022-11-06 22:40 UTC by thaliumFr

#9 mais avec encore plus de truc en gros...

- new design basé sur le Figma
- Nouvelle palette couleur plus uniforme
- mise en place d'un début de Design system
- Compatibilité automatique pour le Darkmode
- Fix des liens GitHub du le footer qui redirigais encore vers l'ancien repos
- Ravalement de surface (et pas que de surface) du CSS
- Mise en place du SCSS
- _et d'autres trucs que j'ai du zapper..._

si vous voulez verifier ca donne [ceci](https://thaliumfr.github.io/ListenPASS/)

Et du coup la PR pour le #9 est inutile maintenant...

2022-11-08 20:03 UTC, NonozgYtb commented on css/listenpass.css
> +/* Repsonsiive */
Repsonsive et pas Repsonsiive 😅

2022-11-08 20:04 UTC, NonozgYtb commented on css/listenpass.scss
> +/* Repsonsiive */
Responsive et pas "Responsiive" 😅

2022-11-08 20:04 UTC, NonozgYtb commented on css/theme.css
> +  --logo: url("../assets/logo-listenpass.svg");
Doit être dans `css/listenpass.css` !!

2022-11-08 20:05 UTC, NonozgYtb commented on css/theme.scss
> +		--logo: url("../assets/logo-dark-listenpass.svg");
Doit être dans `css/listenpass.css` !!

2022-11-08 20:05 UTC, NonozgYtb commented on css/theme.css
> +    --logo: url("../assets/logo-dark-listenpass.svg");
Doit être dans `css/listenpass.css` !!

2022-11-08 20:18 UTC, NonozgYtb requested changes
Très bon boulot, tu a bien réadapté le style depuis le Figma et en plus en Variable CSS !
Quelques changements sont encore à faire (plus des fixs !) et ensuite, on pushera ça dès que c'est fait pour mise en prod rapide !

2022-11-08 20:18 UTC, NonozgYtb commented on css/listenpass.scss
> +/* Repsonsiive */
Repsonsive et pas Repsonsiive 😅

2022-11-08 20:18 UTC, NonozgYtb commented on css/theme.scss
> +	--logo: url("../assets/logo-listenpass.svg");
Doit être dans `css/listenpass.scss`

2022-11-08 20:18 UTC, NonozgYtb commented on css/theme.scss
> +		--logo: url("../assets/logo-dark-listenpass.svg");
Doit être dans `css/listenpass.scss`

2022-11-08 20:18 UTC, NonozgYtb commented on js/base.js
> +	canvas.crossOrigin = "Anonymous";
Tu n'as pas pu le mettre dans le html car ça ne marche pas sinon ?

2022-11-08 20:18 UTC, NonozgYtb commented on passeport.html
> +						<option value="X">Non précisé /optioninaire / Autre</option>
On remplace par `Non précisé / Autre` je pense ?

2022-11-08 21:18 UTC, thaliumFr commented on js/base.js
> +	canvas.crossOrigin = "Anonymous";
je l'ai mis dans les deux comme ca je suis sûr a 300% que ca marche xD

2022-11-08 21:19 UTC, thaliumFr commented on passeport.html
> +						<option value="X">Non précisé /optioninaire / Autre</option>
avec plaisir

2022-11-08 21:19 UTC, thaliumFr commented on passeport.html
> +						<option value="X">Non précisé /optioninaire / Autre</option>
et j'ai fait pareil pour la CNI

2022-11-08 21:21 UTC, thaliumFr commented on css/theme.scss
> +		--logo: url("../assets/logo-dark-listenpass.svg");
seulement le logo je suppose? les couleurs alt peuvent être utiles de partout...

2022-11-09 15:52 UTC, NonozgYtb approved these changes

2022-11-09 15:52 UTC, merged